version: "3"
services:
  postgres-db:
    image: postgres:13-alpine
    restart: always
    environment:
      # TODO create separate user for app, don't use superuser
      POSTGRES_DB: db
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_pass


  redis:
    # TODO setup passwords
    image: redis:6-alpine
    restart: always

  app:
    build: .
    environment:
      NODE_ENV: "production"
      REDIS_DB: db
      REDIS_PORT: 6379
      REDIS_HOST: redis

    depends_on:
      - postgres-db
      - redis
      - migrate
    ports:
      - "127.0.0.1:3000:3000"

  migrate:
    build: .
    depends_on:
      - postgres-db
    command: npx typeorm migration:run
