version: "3.4"
services:
  postgres-db:
    image: postgres:13-alpine
    restart: always
    environment:
      # TODO create separate user for app, don't use superuser
      POSTGRES_DB: db
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    # TODO setup passwords
    image: redis:6-alpine
    restart: always

  app:
    build: .
    environment:
      NODE_ENV: "production"
      REDIS_DB: db
      REDIS_PORT: 6379
      REDIS_HOST: redis

      DB_HOST: postgres-db
      DB_PORT: 5432
      DB_USER: db_user
      DB_PASSWORD: db_pass

    depends_on:
      - postgres-db
      - redis
      - migrate
    ports:
      - "127.0.0.1:3000:3000"

  migrate:
    build:
      context: .
      target: migrations
    depends_on:
      - postgres-db
    environment:
      DB_HOST: postgres-db
      DB_PORT: 5432
      DB_USER: db_user
      DB_PASSWORD: db_pass
    command: ts-node ./node_modules/typeorm/cli.js --config ormconfig.ts migration:run

volumes:
  postgres_data: { }